# Generated by Django 5.2.4 on 2025-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
